name: Publish Remote Config

on:
  push:
    branches:
      - remote_config

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Make static dir
        run: mkdir -p static

      - name: Check for backwards compatibility
        run: |
          KILN_TEST_COMPATIBILITY=1 uv run python3 -m pytest libs/core/kiln_ai/adapters/test_remote_config.py::test_backwards_compatibility_with_v0_19 -s -v

      - name: Generate Config
        run: |
          uv run python -m kiln_ai.adapters.remote_config static/kiln_config_v2.json

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_REMOTE_CONFIG_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_REMOTE_CONFIG_ACCOUNT_ID }}
          command: pages deploy static --project-name=kiln-remote-config
